### ISSUE TITLE
Trying to compile new BIOS with nbasm on Linux / wine

### ISSUE THREAD

**Issue by vruppert** [fysnet/i440fx#1] opened 2024-10-20 06:51 UTC
When I try to compile the new BIOS with wine on Linux, the nbasm exits with the following messages.
Is there a workaround for it?

0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005

NBASM   The NewBasic Assembler      Version  00.27.14 (64-bit)
Forever Young Software(r)       (C)opyright 1984-2024

Z:\home\volker\i440fx\sys_man.asm (   59):  error 21h:  Symbol not defined:  ___
DATE___
Z:\home\volker\i440fx\sys_man.asm (   59):  error 21h:  Symbol not defined:  ___
DATE___
Z:\home\volker\i440fx\sys_man.asm (   59):  error 23h:  Type illegal in context
    Example -------->           Most likely an undefined symbol

       Symbol space free:  5124 symbol(s), 77216 bytes name space
       Error(s) detected:  3
   Diagnostic(s) offered:  0   (.diag == 0)
00dc:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 00007FFFFE1FFD50

**Comment by fysnet** [comment] 2024-10-20 19:26
The `___DATE___` symbol is internal to NBASM. I will have to look into this.

I have no idea what `0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005` is. It looks to be WINE specific and is not an error, more of a warning(?). Try using (?):
```
WINEDEBUG="fixme-all" wine winecfg
```

**Comment by vruppert** [comment] 2024-10-25 11:45
Now I tried it on Win11 and I got the same errors. I would be important for me to build the new BIOS, since I found out that booting from network bootrom fails with it and I'd like to find a fix for it.

D:\Projekte\i440fx>..\nbasm\nbasm64.exe i440fx /z

NBASM   The NewBasic Assembler      Version  00.27.14 (64-bit)
Forever Young Software(r)       (C)opyright 1984-2024

D:\Projekte\i440fx\sys_man.asm (   59):  error 21h:  Symbol not defined:  ___DATE___
D:\Projekte\i440fx\sys_man.asm (   59):  error 21h:  Symbol not defined:  ___DATE___
D:\Projekte\i440fx\sys_man.asm (   59):  error 23h:  Type illegal in context
    Example -------->           Most likely an undefined symbol

       Symbol space free:  5124 symbol(s), 77216 bytes name space
       Error(s) detected:  3
   Diagnostic(s) offered:  0   (.diag == 0)

D:\Projekte\i440fx>

**Comment by fysnet** [comment] 2024-10-25 13:09
I haven't had a chance to look at it yet, sorry, but I will see what is going on as soon as I get a chance. Thank you again for your efforts.

**Comment by fysnet** [comment] 2024-10-25 13:22
P.S. As a work around for now, the symbol '___DATE___' simply equates to the current date in 'mm/dd/yyyy' text form. Replace ___DATE___ with 10/25/2024 and it should build.

**Comment by fysnet** [comment] 2024-10-25 23:01
I can't reproduce the error here. However, there is a difference. Your output is:

       Symbol space free:  5124 symbol(s), 77216 bytes name space
       Error(s) detected:  3
And my output is:

       Symbol space free:  5122 symbol(s), 77170 bytes name space
       Error(s) detected:  0
If you have not modified the source any, why does NBASM64 (on Wine) think you have two more symbols added with a combined symbol space of 46 added bytes?

If you don't mind, please add the `/x` parameter to the command line and send me the resulting `.lst` file. `fys [at] fysnet [dot] net`

**Comment by vruppert** [comment] 2024-10-26 09:34
I ran both build tests (Linux/wine and Win11) with the unmodified source from github. I hope the .lst file helps you to find out what's going on. In the meantime I could build the BIOS with the "date-hack" and found two issues with the boot menu and boot message in the network case. The BEV code 0x80 must be changed to the string index 6. Since booting ends with an IOAPIC panic, there must be something wrong with the entry point, too.

**Comment by fysnet** [comment] 2024-10-26 20:43
The .lst file you sent did not contain the two internal symbols of `___DATE__` and `___DATE___`. For some reason, which I think is due to WINE and/or Linux, might think the three underscores is an issue with UTF-8 or something like this.
Some comments I found about this says to set the `LANG` environment variable to indicate that UTF-8 is supported.

I will look into the BEV code issue.

Thank you

**Comment by fysnet** [comment] 2024-10-26 23:31
(I tried to reply to your email, but it bounced back.)

I have no idea why the `___DATE___` is missing with your build. I compiled `NBASM` on a 32-bit WinXP machine and it built the bios just fine. Two different compilers, two different machines, and same results, each including the `___DATE___` symbol as expected. I have no idea why yours does not.

As for the BEV code issue, change line 346 in boot.asm from:
`      mov  boot_offset,bx`
to
`      mov  boot_offset,ax`
and see if this helps.

**Comment by vruppert** [comment] 2024-10-27 08:15
The change of the boot offset makes network boot work at the end, but before that several IOAPIC panics occur. Please try the test environment I've sent to you. Trying to build the BIOS on a different machine is a good idea. I'll have a look what I can do.

**Comment by fysnet** [comment] 2024-10-28 01:01
Try the latest [commit a8d4b41](https://github.com/fysnet/i440fx/commit/a8d4b415b11565eb1cdd197334fd6efba2ed515c). I added a modified version of your patch to fix the network string display, and found that I never set FS to zero after setting up unreal mode, hence the 0x180 offset from 0xFEC00000, which created the BX_PANIC you were seeing.

**Comment by vruppert** [comment] 2024-10-28 16:23
The network boot works fine now. In the meantime I tried to build the new BIOS on my old Win 10 notebook and it fails with the same errors as on my new one.

**Comment by fysnet** [comment] 2024-10-28 20:49
My wholehearted apologies. I couldn't figure out why you were having this issue and I couldn't reproduce it. Then I decided, just out of curiosity, to try the nbasm64.exe in the downloadable .zip file.  Wouldn't you know it, it had the issue you are describing. Please download the [new .zip file](https://www.fysnet.net/zips/nbasm.zip) and let me know if the issue is now fixed.

So sorry.

**Comment by vruppert** [comment] 2024-10-28 21:35
With the new zip file I just did a quick test with Linux / wine and everything's okay now. Wine brings up some of it's usual warnings, but no more errors. The generated binary is usable for booting to DOS prompt and the network boot. At the moment I don't have an image to test the new USB boot option. Please let me know if there is at least one for download.

**Closed as completed** 2024-10-28 21:36 UTC

**Comment by fysnet** [comment] 2024-10-28 21:57
No special image needed. Simply indicate an image file on one of the four controller types and tell it to boot usb.
For example, I boot a Win95 USB stick like this:
```
 boot: usb
 usb_uhci: port2=disk, options2="speed:full, path:win95.img"
```
The win95.img file is the same file I boot as a HDD. The USB boot option should boot the image telling the OS it is an HDD. The OS should think it is an HDD having no idea that it is actually a USB disk.

As an example, if you already boot Win95 as an HDD, all you have to do is comment out the `ATAx-master` line, add the two lines above and it should boot exactly the same way. You should see no difference, except maybe after Win95 gets to a point were it must to be an HDD. However, at that point, that particular Win95 shouldn't be booted via USB anyway. (An OS that knows it boots from a USB will be different than one that knows it boots from an HDD)

Try any HDD image you already boot as HDD. In all my tests, all my HDD images booted as USB with absolutely no change to the image, and only specifying that the image is now on `USB` instead of `ATAx`.

However, as expected most modern OSes only got so far because they assume they are already on an HDD/SATA/etc. However, any classic OS, Win31, DOS, etc, booted all the way and ran with no errors.

My goal was to make it so the OS had no idea it was booting from an USB, making it think it was HDD all this time. I think that is the goal of most BIOSes.

Try any image and see how far it gets. Any classic/legacy OS should boot without modification, while any modern OS will only get so far.

As always, especially with new and experimental features such as this, a backup of your image file is recommended. :-)

**Comment by fysnet** [comment] 2024-10-28 21:59
P.S. Thank you for your help. It is very appreciated.
